### ISSUE TITLE
mnc2nii requires no transformation input?

### ISSUE THREAD

**Issue by ljc19800331** [BIC-MNI/minc-tools#104]
Hello, I am using the BITE dataset and mnc2nii function to convert the .mnc file to the .nii file. In the dataset, I also get the .tag file. I want to show the .tag fiducials on the .nii file but I am not sure if the mnc2nii function will change any voxel coordinate from the original .mnc file. I am wondering if I need to apply any transformation to the .tag file after converting .mnc to .nii format? Or I just need to use the original .tag file to show the fiducials on the new .nii file? Thanks.

**Comment by gdevenyi** [comment]
The mnc2nii function, when working correctly, applies no transformations or adjustments to the orientation of the file.

You can confirm orientations by using register or Display, both which can open both MINC and NIFTI.

Be aware of this bug, and its workaround, https://github.com/BIC-MNI/minc-tools/issues/99
Fixed in code but not yet in release.

**Comment by ljc19800331** [comment]
@gdevenyi Great thanks. I try the mnc2nii command for the two .mnc files to convert to the .nii files. However. when I also load the .tag file into the 3D slicer, the fiducials are not matched with the .nii files. Is there any additional step I need to do to get the correct .tag file after convertion? 

Step 1: mnc2nii 2u.3dus.mnc 2a.3dus.mnc  --- 1.nii and 2.nii files.
Step 2: Load the 1.nii and 2.nii and .tag file to the 3D slicer but the fiducials are not matched with the volume images.

![test](https://user-images.githubusercontent.com/26176910/76480750-040fe580-63e6-11ea-8ccd-633ace78bd68.png)

**Comment by gdevenyi** [comment]
Please confirm you are not being bitten by #99 by loading the mnc and converted nii files into "register 2u.3dus.mnc 1.nii"
