### ISSUE TITLE
can't be built outside of toolkit due to missing cmake-modules/FindNIFTI.cmake

### ISSUE THREAD

**Issue by bcdarwin** [BIC-MNI/minc-tools#107]

**Comment by gdevenyi** [comment]
Hi @bcdarwin have you tried the https://github.com/BIC-MNI/minc-toolkit-v2/blob/develop-1.9.18/cmake-modules/FindNIFTI.cmake from minc-toolkit-v2? Does it work as-is?

**Comment by bcdarwin** [comment]
> Hi @bcdarwin have you tried the https://github.com/BIC-MNI/minc-toolkit-v2/blob/develop-1.9.18/cmake-modules/FindNIFTI.cmake from minc-toolkit-v2? Does it work as-is?

I tried the one from libminc and it worked.
