### ISSUE TITLE
mnc2nii - Floating point exception (core dumped) error

### ISSUE THREAD

**Issue by cmadjar** [BIC-MNI/minc-tools#109]
I have 3 MINC files (out of 23,587) that fails conversion to NIfTI files with the following error:

```
Floating point exception (core dumped)
```

Full verbose output when using the `-verbose` option:
```
MINC type 5 signed 1
Real range: 0.000000 4095.000000 Input valid range: 0.000000 4095.000000 Output valid range: 0.000000 4095.000000
Resetting output range.
found time at 0 0
found zspace at 1 1
found yspace at 2 2
found xspace at 3 3
0 3 0 1 65 9.300000
1 2 1 1 65 2.000000
2 1 2 1 96 2.000000
3 0 3 1 96 2.000000
<nifti_image
  nifti_type = 'NIFTI-1+'
  header_filename = 'test.nii'
  image_filename = 'test.nii'
  image_offset = '348'
  ndim = '4'
  nx = '96'
  ny = '96'
  nz = '65'
  nt = '65'
  dx = '2'
  dy = '2'
  dz = '2'
  dt = '9.3'
  datatype = '16'
  datatype_name = 'FLOAT32'
  nvox = '38937600'
  nbyper = '4'
  byteorder = 'LSB_FIRST'
  descrip = 'mnc2nii /data/preventad/data/assembly/9258598/PREEN00/mri/native/preventad_92585'
  sform_code = '1'
  sform_code_name = 'Scanner Anat'
  sto_xyz_matrix = '-2 -0 0 93.2574 -0 -2 0 104.133 0 0 2 -41.2589 0 0 0 1'
  sto_ijk matrix = '-0.5 0 0 46.6287 0 -0.5 0 52.0667 0 0 0.5 20.6295 0 0 0 1'
  sform_i_orientation = 'Right-to-Left'
  sform_j_orientation = 'Anterior-to-Posterior'
  sform_k_orientation = 'Inferior-to-Superior'
  num_ext = '0'
/>
Floating point exception (core dumped)
```

The MINC files seem valid and I can perform other manipulation on them (like mincpik, mincheader, mincinfo...). Not sure why these particular files are failing since all the files on that VM were all generated the same way.

Wondering if you encountered something like this in the past and if you would have any pointers as to what I could try.

Thank you!

**Comment by cmadjar** [comment]
Ooops, sorry, I forgot to mention the version of the `mnc2nii` I have installed:

```
[lorisadmin@preventad-open-update tools]$ mnc2nii -version
program: 2.4.04
libminc: 2.4.04
netcdf : 4.5.0 of Jul  1 2019 17:17:29 $
HDF5   : 1.8.20
```

from MINC toolkit 1.9.17

**Comment by gdevenyi** [comment]
Hi,

Please test inside a different environment to exclude specific environment effects.

Can you please also detail how minc-toolkit was installed. Thanks.

**Comment by cmadjar** [comment]
looks like something went wrong with the creation of the binary somehow cause using the same binary from a different VM worked on those files...

Wonder why mnc2nii worked on 23,587 files but not those three. Weird... Anyhow, will close the issue.

Thanks!

**Comment by vfonov** [comment]
Could be related to the fix in mni2nii we made not long time ago: https://github.com/BIC-MNI/minc-tools/issues/90 - maybe you got an old version installed?
