### ISSUE TITLE
Undefined behaviour in mincresample

### ISSUE THREAD

**Issue by bbbxyz** [BIC-MNI/minc-tools#111]
I discovered an array overflow in resample_volume's trilinear_interpolant() while running mincresample on an input volume with a slice dimension size of one. It attempts to read from index `slcind+1` [here](https://github.com/BIC-MNI/minc-tools/blob/develop/progs/mincresample/resample_volumes.c#L733-L738) but `volume->offset` is created with a size of 1
[here](https://github.com/BIC-MNI/minc-tools/blob/master/progs/mincresample/mincresample.c#L693-L697).
I believe the intended behaviour was to use `slcnext` (set to 0 when the dimension is of size 1 [here](https://github.com/BIC-MNI/minc-tools/blob/develop/progs/mincresample/resample_volumes.c#L677-L689) ) rather than `slcind+1` as an index.

To reproduce it:
```
make_phantom -xcenter 1.1 -xwidth 1 -xnelements 1 -xstart 1.1 -xstep 0.005 input.mnc
mincresample input.mnc out.mnc
```
The exact output is undefined and from what I can see depends on your system but running the mincresample call with valgrind should complain about an invalid read.

I'll open a PR if that fix sounds correct to you.

**Comment by vfonov** [comment]
yes, looks like it is an attempt to account for interslice normalization , that's gone wrong. 
fix looks reasonable
