### ISSUE TITLE
'Floating point exception' error using mnc2nii

### ISSUE THREAD

**Issue by Colm2021** [BIC-MNI/minc-tools#114]
Dear Gabriel, 

I am getting a 'Floating point exception' error when trying to convert a 4D .mnc file to a .nii file using mnc2nii. 

Here is the mincinfo input for the input file:
file: FAL_EEG_001_PETs_1to3_stepcorrected_reshaped_realigned_corrected_DCed.mnc
image: unsigned short 0 to 65535
image dimensions: time zspace yspace xspace
    dimension name         length         step        start
    --------------         ------         ----        -----
    time                      161           90          -60
    zspace                    127     -2.03125      128.281
    yspace                    256     -1.40171      178.834
    xspace                    256     -1.40171      179.895

Here is the command and returned error: 
mnc2nii -nii FAL_EEG_001_PETs_1to3_stepcorrected_reshaped_realigned_corrected_DCed.mnc FAL_EEG_001_PETs_1to3_stepcorrected_reshaped_realigned_corrected_DCed_mnc2nii.nii
found time at 0 0
found zspace at 1 1
found yspace at 2 2
found xspace at 3 3
0 3 0 1 161 90.000000
1 2 1 1 127 2.031254
2 1 2 1 256 1.401710
3 0 3 1 256 1.401710
Floating point exception

I have tried specifying the output type, e.g. -unsigned, but I got the same error.

I am using mincversion 2.4.02 on Ubuntu 16.04.7.

Thanks in advance for your help,
Thanks and best wishes,
Colm

**Comment by vfonov** [comment]
could be fixed in https://github.com/BIC-MNI/minc-tools/issues/109

**Comment by gdevenyi** [comment]
As per @vfonov 

The latest version is
```
$ mincinfo -version
program: 2.4.05
libminc: 2.4.05
netcdf : 4.7.4 of Mar 18 2021 13:32:14 $
HDF5   : 1.10.6
```

Please try the latest release. Packages for the major supported platforms are available at https://bic-mni.github.io/

Also please let us know from where you got your current install.

**Comment by Colm2021** [comment]
Hello,

Thank you very much for your help.
I was using 1.9.16. 
I have installed 1.9.18 now and it seems to be working correctly,

Thanks again and best wishes,
Colm
