### ISSUE TITLE
Use min-tools on Win10

### ISSUE THREAD

**Issue by Leong1230** [BIC-MNI/minc-tools#116]
Hi!
Dose minc-tools have any version that supports Win10 (64-bit)？
The compatibility issues with the executable files stopped me from trying command like "minchead". (Download from http://www.bic.mni.mcgill.ca/ServicesSoftware/MINC).

Do you have any suggestion?

**Comment by gdevenyi** [comment]
Hi,

We do not support Windows as a primary platform. You may be interested in either WSL to run Ubuntu inside windows, or https://github.com/cobralab/MINC-VM which uses VirtualBox.
