### ISSUE TITLE
Compile fails on Mac 10.9 64bit

### ISSUE THREAD

**Issue by reckbo** [BIC-MNI/minc-tools#22]
I installed libminc, then tried to build minc-tools, but get this error:

make
[  1%] Built target invert_raw_image
Linking C executable minc_modify_header
Undefined symbols for architecture x86_64:
  "_MI2attdel", referenced from:
      _main in minc_modify_header.c.o
  "_MI2attget", referenced from:
      _main in minc_modify_header.c.o
  "_MI2attinq", referenced from:
      _main in minc_modify_header.c.o
  "_MI2attput", referenced from:
      _main in minc_modify_header.c.o
  "_MI2redef", referenced from:
      _main in minc_modify_header.c.o
  "_MI2sync", referenced from:
      _main in minc_modify_header.c.o
  "_MI2typelen", referenced from:
      _main in minc_modify_header.c.o
  "_MI2vardef", referenced from:
      _main in minc_modify_header.c.o
  "_MI2varid", referenced from:
      _main in minc_modify_header.c.o
  "_miclose", referenced from:
      _main in minc_modify_header.c.o
  "_micreate_group_variable", referenced from:
      _main in minc_modify_header.c.o
  "_miexpand_file", referenced from:
      _main in minc_modify_header.c.o
  "_miopen", referenced from:
      _main in minc_modify_header.c.o
  "_ncopts", referenced from:
      _main in minc_modify_header.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: **\* [progs/minc_modify_header] Error 1
make[1]: **\* [progs/CMakeFiles/minc_modify_header.dir/all] Error 2
make: **\* [all] Error 2

Any idea what the problem is?

**Comment by vfonov** [comment]
Try building https://github.com/BIC-MNI/minc-toolkit
