### ISSUE TITLE
Problem with spm realign

### ISSUE THREAD

**Issue by Angel-Fernandez** [BIC-MNI/minc-tools#23]
Hi @andrewjanke 

I've a problem with spm_realign. I'm trying to obtain movement parameters using the mean image. I've tried all  (flags.rtm equal 1, 0 or [ ]) and always obtain the same result respect the first volume. 

![traslaciones](https://cloud.githubusercontent.com/assets/10339281/7743505/ca36afaa-ff9b-11e4-9882-0b847c7c51ff.png)

This is my code:

     flags.rtm=1;
     spm_realign(P,flags);

What I'm doing wrong?

Thanks and best regards.

**Comment by andrewjanke** [comment]
Hi Angel,

I'm not quite sure if you meant this message to end up here. My guess
is that you want the SPM mailing list.

a
