### ISSUE TITLE
Build Fails Ubuntu 12.04

### ISSUE THREAD

**Issue by cfhammill** [BIC-MNI/minc-tools#28]
I'm trying to install libminc and minc-tools on a ubuntu 12.04 virtual machine

`cmake .` 

> CMake Error at CMakeLists.txt:42 (FIND_PACKAGE):
>  Could not find module FindLIBMINC.cmake or a configuration file for package
>  LIBMINC.
> 
>  Adjust CMAKE_MODULE_PATH to find FindLIBMINC.cmake or set LIBMINC_DIR to
>  the directory containing a CMake configuration file for LIBMINC.  The file
>  will have one of the following names:
> 
>    LIBMINCConfig.cmake
>    libminc-config.cmake
> 
> CMake Error at CMakeLists.txt:46 (INCLUDE):
> include called with wrong number of arguments.  Include only takes one
>  file.

so I tried (after removing CMakeCache)
`cmake . -DLIBMINC_DIR=$HOME/libminc/ # where LIBMINCConfig lives`
and 
`cmake . -DLIBMINC_DIR=/usr/local/lib # the install path`

both of which configure, but then make fails in both cases with 

> /usr/bin/ld: cannot open output file minc_modify_header: Is a directory 
> collect2: ld returned 1 exit status
> make[2]: **\* [progs/minc_modify_header] Error 1

**Comment by vfonov** [comment]
I suggest building https://github.com/BIC-MNI/minc-toolkit

**Comment by vfonov** [comment]
And also use a separate build diretory

**Comment by cfhammill** [comment]
building in a subdirectory fixed the problem, thanks
