### ISSUE TITLE
Reordering dimensions like a reference volume

### ISSUE THREAD

**Issue by ajwood** [BIC-MNI/minc-tools#35]
I was wondering if it might be a good idea to add something that could reorder dimensions like a reference volume (e.g. a step needed before passing a zxy volume and an xyz volume to mincmath). Of course this would only work if the volumes have the same sampling and are just stored in a different order.

I wondered if a natural place for this would be adding a "-like" option to mincreshape?

**Comment by vfonov** [comment]
mincreshape input.mnc -dimorder $(mincinfo -vardims image reference.mnc|tr ' ' ',') output.mnc
