### ISSUE TITLE
minclookup loses quotes around lut_string when saving history

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/minc-tools#45]
Original command was:

```
> minclookup -lut_string "201 201" -discrete brain1_jg_label.mnc brain1_jg_201.mnc -clobber
```

But history shows:

```
> minclookup -lut_string 201 201 -discrete \
     brain1_jg_label.mnc brain1_jg_201.mnc -clobber
```

With the quotes missing the command is "broken"

**Comment by gdevenyi** [comment]
This may be a shell issue, that minclookup never sees the quotes, but it should insert some in the history perhaps?

**Comment by rdvincent** [comment]
This is partially a shell issue - but at a minimum we should probably restore quotes around strings that contain spaces.

**Comment by rdvincent** [comment]
@gdevenyi I checked in a fix for this, which I think is sufficient for most cases.

**Comment by gdevenyi** [comment]
Fixed
