### ISSUE TITLE
mincreshape can't do non-integer slice steps

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/minc-tools#48]
Slices steps for -dimsize are attempted to be parsed as integers, so you can never use non-integer slicing

https://github.com/BIC-MNI/minc-tools/blob/master/progs/mincreshape/mincreshape.c#L601-L609

**Comment by vfonov** [comment]
dimsize supposed to represent number of slices in the given dimension. How can you have non-integer number of slices?

**Comment by gdevenyi** [comment]
Oops, seems I completely misinterpreted the parameter. Sorry for the noise.
