### ISSUE TITLE
Feature Idea: mincheader query specific item

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/minc-tools#65]
Similar to minc_modify_header, it would be nice if there were a way to dump a single header item.

**Comment by vfonov** [comment]
`mincinfo -attvalue <variable>:<attribute>  ...` ?

**Comment by gdevenyi** [comment]
That is indeed what I'm looking for.

Thought it might be in mincheader or minc_modify_header. Never thought of mincinfo.

Sorry!
