### ISSUE TITLE
dcm2mnc and JPEG compression

### ISSUE THREAD

**Issue by andrewjanke** [BIC-MNI/minc-tools#67]
I note that dcm2mnc will silently fail on images with JPEG compression (you get black/blank images). Specifically ones that say things like this:

`# Dicom-Data-Set`
`# Used TransferSyntax: JPEG Lossless, Non-hierarchical, 1st Order Prediction`

I recognise that this is a licencing thing, meaning we'd have to include a JPEG licence in dcm2mnc to make this happen but am curious if others have ways around this. OSIRIX is one way, fork a decode process to something else?

For now I do something like this:

`for i in `ls -1 *.dcm`; do dcmdjpeg $i unjpg/$i; done`

And then the conversion is all fine. Can we link/call/something dcmdjpeg?

**Comment by rdvincent** [comment]
There is actually some code in there now to handle jpeg compression, and to crash if the compression is something we don't know how to handle. There are open-source libraries for most of the useful transfer encodings.

**Comment by andrewjanke** [comment]
Ah, in the develop branch.

https://github.com/BIC-MNI/minc-tools/commit/157d0532dd137e21147ee3de6a92e77f37463457

I shall give it a whirl.


a

**Comment by vfonov** [comment]
fixed by https://github.com/BIC-MNI/minc-tools/commit/157d0532dd137e21147ee3de6a92e77f37463457
