### ISSUE TITLE
mnc2nii appears to give incorrect scaling

### ISSUE THREAD

**Issue by matthew-brett** [BIC-MNI/minc-tools#8]
In writing my MINC2 conversion, I noticed that I think `mnc2nii` is getting the image scaling wrong.  For example, if I do this:

```
mincstats mincex_pd.mnc
```

on an example file given to me by Andrew Janke, I get this:

```
Min:               0
Max:               102.5024482
Sum:               102940629.4
Sum^2:             5570867979
Mean:              23.82625718
```

among other stuff.  But, when I do this:

```
mnc2nii mincex_pd.mnc converted_pd.nii
```

and load the data in nibabel or SPM, I get:

```
python -c 'import nibabel; img = nibabel.load("converted_pd.nii");
print(img.get_data().mean())'

51.2892728726
```

So - I think the scaling is incorrect for the generated nifti files.

**Comment by gdevenyi** [comment]
Tested with latest versions, fixed.
