### ISSUE TITLE
minclookup does not support -labels

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/minc-tools#91]
minclookup's -discrete setting does not enforce the "no renormalization" needed to avoid messing up label numbers and -discrete doesn't turn on that handling either.

**Comment by gdevenyi** [comment]
Looks like based on https://github.com/BIC-MNI/minc-tools/commit/cc03c467df866a76f8a7eb0115ddc0fa10651fa1 its quite easy to add.

Does it make more sense to attach it to the -discrete option or add a -labels option (or both?)

**Comment by vfonov** [comment]
I would say it should be attached to both.

**Comment by gdevenyi** [comment]
will do!

**Comment by stilley2** [comment]
Hi all,

Is there an easy workaround for this until the changes make it upstream?

Thanks!

**Comment by gdevenyi** [comment]
`` mincreshape -normalize -unsigned -byte -image_range 0 255 -valid_range 0 255 output_from_minclookup.mnc fixed.mnc``

**Comment by gdevenyi** [comment]
Fixed by #92

**Comment by stilley2** [comment]
Thanks!
