### ISSUE TITLE
dcm2mnc binary versions

### ISSUE THREAD

**Issue by cmadjar** [BIC-MNI/minc-tools#94]
Hi,

This is not really an issue but a general question for MINC developers.

To release open datasets, we had to use a specific `dcm2mnc` version that was compiled by Bert on CentOS and Ubuntu when he fixed an issue we encountered with the current `dcm2mnc`. I see that the code changes have been integrated in the github repository but it is not part of the latest MINC toolkit. I guess it will be part of the next release, along with other bug fixes.

Since it was used as part of the release of an open dataset, we would like to document this `dcm2mnc` binary and give it a URL, DOI, name + version. Maybe on Zenodo? Is this something we could do? Do you have any suggestion as to what we could do?

Let me know. Thank you!
Best,

Cécile

**Comment by gdevenyi** [comment]
You could fork minctools, tag the commit that is the version you used, and emit your own DOI using Zenodo on the repository.

**Comment by cmadjar** [comment]
Cool! Thank you for the hint!

One other question if I may. To create the dcm2mnc binaries, how one would do it? Never done it myself but it feels like something that could be helpful to know.

Thanks!

**Comment by gdevenyi** [comment]
if you do a static build you can just post the binary directly and it should just be runnable for most linux folks.

**Comment by cmadjar** [comment]
Perfect. Thank you for your help!
